spring:
  application:
    name: eureka-server

server:
  port: 8761

logging:
  level:
    com.netflix: DEBUG

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761
  server:
    renewal-percent-threshold: 0.49
    enable-self-preservation: false