{
 "title": "Time Entry Controller",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Controller Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "timesheets_controller_create_timer_seconds"
    }
   ]
  },
  {
   "title": "Exception Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(timesheets_controller_exceptions_count_total[$__interval])"
    }
   ]
  },
  {
   "title": "Health Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "timesheets_controller_health_status"
    }
   ]
  }
 ]
}